apiVersion: v1
kind: Pod
metadata:
  name: auto-test
spec:
  containers:
  - name: auto-test
    image: autotest:0.1.0
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /home/autotest/aistack
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /root/autotest/aistack
  nodeSelector:
    kubernetes.io/hostname: k8s-node1
