apiVersion: v1
kind: Pod
metadata:
  name: kube-cephfs
spec:
  containers:
  - name: cephfs-rw
    image: busybox
    command: ["sleep", "60000"]
    volumeMounts:
    - mountPath: "/mnt/cephfs"
      name: cephfs
  volumes:
  - name: cephfs
    cephfs:
      monitors:
      - mon-hosts:6789 
      user: admin 
      path: /
      secretRef:
        name: ceph-secret
