---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  mysql-accross
  namespace: openstack

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mysql-accross
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mysql-accross
subjects:
- kind: ServiceAccount
  name:  mysql-accross
  namespace: openstack
roleRef:
  kind: ClusterRole
  name: mysql-accross
  apiGroup: rbac.authorization.k8s.io
