kind: Service
apiVersion: v1
metadata:
  name: mariadb-server
  namespace: openstack
spec:
  selector:
    application: mariadb
    component: server
    release_group: mariadb
  ports:
  - name: mysql
    port:  3306
    targetPort: 3306
