apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx
  namespace: default
  labels:
    k8s-app: nginx
spec:
  template:
    metadata:
      labels:
        name: k8s-nginx
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: my-nginx
          image: nginx
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
            